swagger: "2.0"
info:
  version: 1.0.0
  title: swagger-doc-demo
host: localhost:10101
basePath: /api/v1
schemes:
- http
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /users:
    get:
      summary: 获取所有的用户
      responses:
        200:
          description: 返回所有用户信息
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                gender:
                  type: integer
                  format: int32
                  enum:
                  - 0
                  - 1
                email:
                  type: string
                avatar:
                  type: string
                nickname:
                  type: string
                role:
                  type: integer
                  format: int32
                phone:
                  type: string 
                create_time:
                  type: string
                  format: date-time
                update_time:
                  type: string
                  format: date-time
                isValidate:
                  type: boolean
      

