swagger: '2.0'
info:
  version: 1.0.0
  title: swagger-doc-demo
host: 'localhost:10101'
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - application/octet-stream
  - multipart/form-data
produces:
  - application/json
  - application/octet-stream
paths:
  /users:
    get:
      summary: 获取所有的用户
      responses:
        '200':
          description: 返回所有用户信息
          schema:
            type: array
            x-swagger-maxItems: 5
            x-swagger-minItems: 1
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                gender:
                  type: integer
                  format: int32
                email:
                  type: string
                  format: email
                avatar:
                  type: string
                  x-swagger-format: image
                nickname:
                  type: string
                role:
                  type: integer
                  format: int32
                phone:
                  type: string
                  x-swagger-format: phone
                create_time:
                  type: string
                  format: date-time
                update_time:
                  type: string
                  format: date-time
                isValidate:
                  type: boolean
